# Mouse functionality disabled for this version.
CONFIG_ZMK_POINTING=n

# Standard Corne I2C SSD1306 128x32 OLED on each half.
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_BUILT_IN=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=y

# Activity timeout for OLED blanking (milliseconds).
CONFIG_ZMK_IDLE_TIMEOUT=1000
