// HID equivalents of the original QMK aliases; host layout is unchanged.
#pragma once
#define ES_PIPE    GRAVE
#define ES_QUOT    MINUS
#define ES_IQUE    EQUAL
#define ES_ACUT    LEFT_BRACKET
#define ES_PLUS    RIGHT_BRACKET
#define ES_ENIE    SEMICOLON
#define ES_LCBR    SINGLE_QUOTE
#define ES_RCBR    NON_US_HASH
#define ES_LABK    NON_US_BACKSLASH
#define ES_COMM    COMMA
#define ES_DOT     DOT
#define ES_MINS    SLASH
#define ES_MORD    LS(ES_PIPE)
#define ES_EXLM    LS(N1)
#define ES_DQUO    LS(N2)
#define ES_NUMB    LS(N3)
#define ES_DLR     LS(N4)
#define ES_PERC    LS(N5)
#define ES_AMPR    LS(N6)
#define ES_SLSH    LS(N7)
#define ES_LPRN    LS(N8)
#define ES_RPRN    LS(N9)
#define ES_EQL     LS(N0)
#define ES_QUES    LS(ES_QUOT)
#define ES_IEXL    LS(ES_IQUE)
#define ES_DIAE    LS(ES_ACUT)
#define ES_ASTR    LS(ES_PLUS)
#define ES_LBRC    LS(ES_LCBR)
#define ES_RBRC    LS(ES_RCBR)
#define ES_RABK    LS(ES_LABK)
#define ES_SCLN    LS(ES_COMM)
#define ES_COLN    LS(ES_DOT)
#define ES_UNDS    LS(ES_MINS)
#define ES_NOT     RA(ES_PIPE)
#define ES_BSLS    RA(ES_QUOT)
#define ES_ARRO    RA(Q)
#define ES_VIRG    RA(ES_PLUS)
#define ES_CIRC    RA(ES_LCBR)
#define ES_GRV     RA(NON_US_HASH)
